-- Migration 002: Add recommender scoring and pointer columns to menu_items
-- Corresponds to qrate-core migration 019_add_margin_upsell.sql

ALTER TABLE menu_items
    ADD COLUMN IF NOT EXISTS margin_score DECIMAL(3,1) DEFAULT 5.0
        CHECK (margin_score >= 1.0 AND margin_score <= 10.0);

ALTER TABLE menu_items
    ADD COLUMN IF NOT EXISTS upsell_pointers UUID[] DEFAULT '{}';

ALTER TABLE menu_items
    ADD COLUMN IF NOT EXISTS cross_sell_pointers UUID[] DEFAULT '{}';

-- Optional: GIN index on pointer arrays for fast containment queries
CREATE INDEX IF NOT EXISTS menu_items_upsell_gin_idx
    ON menu_items USING GIN (upsell_pointers);

CREATE INDEX IF NOT EXISTS menu_items_cross_sell_gin_idx
    ON menu_items USING GIN (cross_sell_pointers);

COMMENT ON COLUMN menu_items.margin_score IS
    'Profit margin score 1.0-10.0, generated by ops team or cost calculator';
COMMENT ON COLUMN menu_items.upsell_pointers IS
    'Array of menu_item UUIDs to suggest as premium upsells after this item is recommended';
COMMENT ON COLUMN menu_items.cross_sell_pointers IS
    'Array of menu_item UUIDs (typically drinks/sides) to suggest after item acceptance';
