from pydantic import BaseModel, Field
from typing import Optional
from uuid import UUID
import decimal


class UpsellPointer(BaseModel):
    item_id: UUID
    reason: str = ""


class MarginScore(BaseModel):
    item_id: UUID
    score: float = Field(..., ge=1.0, le=10.0, description="Profit margin score 1-10")


class MenuItem(BaseModel):
    id: UUID
    restaurant_id: UUID
    name: str
    description: Optional[str] = None
    price: Optional[float] = None
    food_tags: dict = Field(default_factory=dict)
    # food_tags structure (generated by Claude elsewhere):
    # { "allergens": ["nuts", "dairy"], "dietary": ["vegetarian"],
    #   "flavors": ["spicy", "crunchy"], "cuisine": "mexican" }
    margin_score: float = Field(default=5.0, ge=1.0, le=10.0)
    upsell_pointers: list[UUID] = Field(default_factory=list)
    cross_sell_pointers: list[UUID] = Field(default_factory=list)
    # embedding_vector stored in DB only — not serialized through API

    class Config:
        from_attributes = True
